### ISSUE TITLE
Imaginary unit `j` yields syntax error

### ISSUE THREAD

**Issue by HaHeho** [kornilova203/matlab-IntelliJ-plugin#106]
In Matlab it is viable to specify the imaginary unit by `i` or `j` according to varying conventions in different mathematical applications.
```Matlab
a = 1 + 2i;
b = 1 + 2j;
```

However, the second line yields a syntax error with
`'&', '&&', ''', '(', '*', '+', '++', '-', '--', '.'', '.*', '...', './', '.\', '.^', '/', ':', <, <=, '=', '==', '>', '>=', '\', '^', '|', '||' or '~=' expected, got 'j'`

**Comment by kornilova203** [comment]
Fixed by #114
