### ISSUE TITLE
Resolve references across multiple files

### ISSUE THREAD

**Issue by kornilova203** [kornilova203/matlab-IntelliJ-plugin#24]

**Comment by tscheburaschka** [comment]
This would require the option to specify a list of search paths of files to look at (à la Matlab). And once we're introducing options, it would be nice to have the indent size adjustable.

**Comment by kornilova203** [comment]
Hi @tscheburaschka,
You can go to **Settings (Preferences) | Editor | Code Style | Other File Types** and set indent size there. But it will also affect text files and unsupported file types.

**Comment by kornilova203** [comment]
Resolve references in a project #70 #91
