### ISSUE TITLE
Comment block delimiters must be alone on their line

### ISSUE THREAD

**Issue by dullin** [kornilova203/matlab-IntelliJ-plugin#27]
The current parser doesn't respect MATLAB [comment rules](https://www.mathworks.com/help/matlab/matlab_prog/comments.html), the block comment delimiters must be alone on their line or they won't be parsed as delimiters by MATLAB.

The current parser detects a comment block delimiter even if the delimiter is not alone on the line.

```
%{
if ok > 3
    var = 4;
end%}

disp(var)
```

In MATLAB, the `disp(var)` statement will be commented out and in the plugin it will not.

**Comment by kornilova203** [comment]
Good catch! I'll fix it now
