### ISSUE TITLE
Some parser errors

### ISSUE THREAD

**Issue by crisluengo** [kornilova203/matlab-IntelliJ-plugin#37]
These three lines are legal syntax but show an error:

    [V,~] = eig(S);   % at the bracket after the `~`: "'...' or <expression> expected, got ']'"
    t = V{:,ii};      % "':' unexpected"
    pxsz(end+1:length(v)) = pxsz(end); % at the `+`: "',' or '...' expected, got '+'"

Similarly, in a function definition,

    function res = istensor(~)

gives an error for unexpected `~` (it indicates that one input argument is accepted but not used).

---

In `classdef` files,

    properties (Access=private)

is parsed correctly, but

    properties (Dependent)

shows an error at the closing bracket saying "'=' expected".

The setter function

    function img = set.Array(img,data)

shows an error at the dot: "'.' unexpected". The same is true for getter methods, which start with `get.`.

When overloading the `end` function, the parser also throws a fit:

    function ii = end(a,k,n)

It seems that `end` is marked as a reserved keyword. It is true that it is not legal to use it as a variable name, but it is OK as a function name because it can be overloaded for custom classes.

---

Yes, MATLAB syntax is terrible... :)

**Comment by kornilova203** [comment]
Wow! Thanks for so many cases!

**Comment by ghost** [comment]
Here are some additional cases, where the syntax is correct, but the parser shows an error:

**Property Attribut Meta Class**
The property attribute referencing another class (e.g. ?EnvelopeStageManager) as described
[here](https://www.mathworks.com/help/matlab/ref/meta.class.html) and [here](https://www.mathworks.com/help/matlab/matlab_oop/property-attributes.html) is falsly flagged as invalid: `<expression> expected; got ?`

```
classdef
    properties (SetAccess = ?EnvelopeStageManager, GetAccess=public)
        % empty
    end
end
```

**Referencing the function of a static method**
When referencing a static function of a class the dot "." gets marked as unexpected.

`f = @EnvelopeStageManager.printStageInfo;`

**Static keyword not recognized**
When methods are marked as static, the parser expects a "=" after it.
[method attributes](https://www.mathworks.com/help/matlab/matlab_oop/method-attributes.html)
```
methods (Static, Access = protected)
    %empty
end
```

**Getter and Setter methods not recognized**
When getter and setter methods are provided the dot "." gets marked as unexpected.
[property get methods](https://www.mathworks.com/help/matlab/matlab_oop/property-get-methods.html) [property set methods](https://www.mathworks.com/help/matlab/matlab_oop/property-set-methods.html)
```
methods
        function obj = set.initial_amplitude(obj,amplitude)
            obj.initial_amplitude = amplitude;
        end
        
        function a = get.initial_amplitude(obj)
            a = obj.initial_amplitude;
        end
end
```

**Comment by kornilova203** [comment]
I fixed some of them

1. tilda in function parameters b24cf9189dabc999fe8fcbbfa5ca257f28a694df
2. tilda in groped return values 2f29aedcd1270dcfded440f8987a93489fe9a20e
3. cell arrays d7910870c7bf4d9cf6c87742e335e69264e64e04
4. meta classes, getters/setters, property attributes without values 34bc00b4816cea050baef8f73949fcc0aaad1963

**Comment by crisluengo** [comment]
I appreciate this immensely. It is fantastic being able to work on both the C++ and MATLAB portions of my project in the same editor!

**Comment by kornilova203** [comment]
And the last one:
Allow `end` as function name 8daf8c505bbc72a627d84cd69401efc5856ae480
