### ISSUE TITLE
Support for "after the ellipsis" comments

### ISSUE THREAD

**Issue by dims12** [kornilova203/matlab-IntelliJ-plugin#39]
Matlab treats everything after line continuation characters (which is three dots, ellipsis) as a comment. Unfortunately, Matlab plugin doesn't understand this:

![image](https://user-images.githubusercontent.com/5513817/51252331-96685500-19ac-11e9-9c20-bda801f28d13.png)

**Comment by kornilova203** [comment]
Thanks for the report!
It will be fixed in next version

**Comment by kornilova203** [comment]
Fixed by 9506cf4e9a9b9745a84e5704b1a36d845804b4ac
<img width="312" alt="image" src="https://user-images.githubusercontent.com/23450724/51387927-e96f1300-1b38-11e9-9995-5ca6c3fb6ce9.png">
