### ISSUE TITLE
Install matlab-IntelliJ-plugin from local file

### ISSUE THREAD

**Issue by omricarmi** [kornilova203/matlab-IntelliJ-plugin#40]
Hi,
I have a computer that is not connected to the internet.
how can I download the plugin on another computer,
and then move it and install on the offline computer?

**Comment by kornilova203** [comment]
You may download `matlab-IntelliJ-plugin.jar` file from plugin page https://plugins.jetbrains.com/plugin/10941-matlab-support or from [release page](https://github.com/kornilova-l/matlab-IntelliJ-plugin/releases).
To install it open **Plugins** tab in IDEA settings then click on cogwheel icon in top right corner and choose **Install Plugin from Disk**

**Comment by omricarmi** [comment]
Thanks for fast response.
