### ISSUE TITLE
Not recognizing complex conjugate transpose operator

### ISSUE THREAD

**Issue by ghost** [kornilova203/matlab-IntelliJ-plugin#41]
The operator referred to, https://www.mathworks.com/help/matlab/ref/ctranspose.html
The plugin has no problem recognizing `.'`, which is the transpose operator. But it has problems with `'`.

**Comment by kornilova203** [comment]
Hi @HarryLin2,

Thank you for the report!
Could you please add an example where `'` is not recognized?

**Comment by ghost** [comment]
@kornilova-l Sorry, I thought that this was a general case. Through testing, it seems the scenario is rather specific.

Here's the example, `func_a(cell_a{1}')`, where `func_a` is a function and `cell_a` is a cell.

**Comment by kornilova203** [comment]
Thank you
`'` operator is a tricky because `'` may also be a beginning of a string literal. Lexer should be aware of operator position.
I will improve this

**Comment by kornilova203** [comment]
Here is lexer code for `'` in Octave https://github.com/NexMirror/Octave/blob/master/libinterp/parse-tree/lex.ll#L1388-L1456
