### ISSUE TITLE
Doesn't recognize programmatic name fields access in structures

### ISSUE THREAD

**Issue by dims12** [kornilova203/matlab-IntelliJ-plugin#42]
Looks like tool doesn't expect syntax like

`my_structure.(var_with_my_field_name)`

Example

![image](https://user-images.githubusercontent.com/5513817/51464942-c7170880-1d77-11e9-8322-c1a3a8764975.png)

**Comment by kornilova203** [comment]
Thank you for the report
The problem will be fixed in next version

**Comment by dims12** [comment]
Thank you for the tool :)

**Comment by kornilova203** [comment]
Fixed by #45
