### ISSUE TITLE
support try/catch blocks

### ISSUE THREAD

**Issue by tscheburaschka** [kornilova203/matlab-IntelliJ-plugin#44]
Matlabs try/catch blocks are not recognized and the corresponding "end" confuses all other block statement parsing.
This breaks a lot of the plugins tools in my code.

**Comment by kornilova203** [comment]
Thank you for reporting, I’ll fix it in next version

**Comment by kornilova203** [comment]
Fixed by cfaa6731e20dfa1c62ae1735f0225636b6f1c8a3
