### ISSUE TITLE
'exit;' should be optional in run command script

### ISSUE THREAD

**Issue by shamakhov** [kornilova203/matlab-IntelliJ-plugin#46]
... because it closes plots, for example. But I guess it's a minor issue for now.

**Comment by kornilova203** [comment]
Okay, I didn’t knew it, thank you for submitting the issue!

**Comment by sameer9406** [comment]
I installed this plugin today I am not able to get the plots, is there any way I can get the plots?

**Comment by kornilova203** [comment]
Closed by #72
