### ISSUE TITLE
Fieldnames of struct arrays are falsely interpreted as keywords

### ISSUE THREAD

**Issue by tscheburaschka** [kornilova203/matlab-IntelliJ-plugin#50]
### Observation
In the example below, all except the first fieldname are falsely interpreted as keywords (similiarly to the highlighting parser of github, who apparently gets the "end" wrong). Consequently several syntax errors are reported and all following code is broken.

``` matlab
function test_func()

if condition
    s = struct();
    s.start = 3.0;
    s.end = 10.0;
    s.catch = 'Attention!';
    s.if = 'Not breaking anything.';
end

end
```
### Expected behaviour
Keywords that are fieldnames of structs should not be recognized with their keyword meaning.

**Comment by kornilova203** [comment]
Fixed by #66
