### ISSUE TITLE
Logical class-/property-/method-attributes can be specified without an expression

### ISSUE THREAD

**Issue by tscheburaschka** [kornilova203/matlab-IntelliJ-plugin#52]
### Observation
In class definitions many of the class attributes (or the method attributes or property attributes) are of type logical (true or false) and Mathworks documents a widely used shortcut for their specification, namely omitting the expression and only referencing the attribute name.
To quote directly from the [documentation](https://www.mathworks.com/help/matlab/matlab_oop/specifying-attributes.html):
> Simpler Syntax for true/false Attributes
> You can use a simpler syntax for attributes whose values are true or false — the attribute name 
> alone implies true and adding the not operator (~) to the name implies false. For example:
> 
> methods (Static)
>    ...
> end
> Is the same as:
> 
> methods (Static = true)
>    ...
> end
> Use the not operator before an attribute name to define it as false:
> 
> methods (~Static) 
>    ...
> end
> Is the same as:
> 
> methods (Static = false)
>    ...
> end
> All attributes that take a logical value (that is, true or false) have a default value of false. Therefore, specify an attribute only if you want to set it to true.

**Comment by kornilova203** [comment]
This case is not supported:
```matlab
classdef A
   methods (~Static)
   ...
   end
end
```
It can be fixed in Matlab.bnf

**Comment by kornilova203** [comment]
Fixed by #64
