### ISSUE TITLE
Enable folding of code blocks

### ISSUE THREAD

**Issue by tscheburaschka** [kornilova203/matlab-IntelliJ-plugin#53]
### Feature request
Like in other language styles, it would be very useful to be able to fold code blocks (if-else, classdef, try-catch, switch etc).

**Comment by kornilova203** [comment]
We need to implement `class MatlabFoldingBuilder extends CustomFoldingBuilder`
And register it in `plugin.xml` like this: `<lang.foldingBuilder language="Matlab" implementationClass="..."/>`
Example can be found in `XmlCodeFoldingBuilder`

<img width="815" alt="Screenshot 2020-07-01 at 14 26 01" src="https://user-images.githubusercontent.com/23450724/86238863-f9e94100-bba6-11ea-948e-ca9175e44a41.png">

**Comment by kornilova203** [comment]
Closed by #63
