### ISSUE TITLE
Matlab hijacks execution flow

### ISSUE THREAD

**Issue by zolotov** [kornilova203/matlab-IntelliJ-plugin#56]
`MatlabProgramRunner` can run **any** run configurations with **any** executor and it's not the latest extension. This affects every language that does not rely on `DefaultProgramRunner`. E.g. https://youtrack.jetbrains.com/issue/GO-7202.

Other affected executors (minimal set of plugins)

![image](https://user-images.githubusercontent.com/140920/57622270-e25f8b00-7595-11e9-995a-e17a7c51e177.png)

**Comment by zolotov** [comment]
one more https://youtrack.jetbrains.com/issue/GO-7466

**Comment by kornilova203** [comment]
Fixed by ad13ae87d907d493000980928f20ec9b52dd7aaf

I'll leave a comment in youtrack issues when new version is uploaded to plugins repo
