### ISSUE TITLE
Matlab terminal

### ISSUE THREAD

**Issue by YotamLif** [kornilova203/matlab-IntelliJ-plugin#60]
Hi,

Is there a way to open a matlab terminal (running on windows) inside the IDE?
I've tried to set 
   Tools-> terminal-> application settings -> shell path 
to
  "MATLABROOT\MATLAB.exe" -nojvm
But it opens a new matlab command window which isn't inside the IDE terminal.

Thanks

**Comment by kornilova203** [comment]
Hello!
What if you open a terminal tool window (View | Tool Windows | Terminal)
and start matlab terminal there?
Will it solve the problem?
Here is a screenshot of Octave interpreter in terminal window inside IDE:

<...>

**Comment by YotamLif** [comment]
Thanks for the quick response.
What do you mean by "start matlab terminal there"? which command runs matlab terminal inside cmd.exe (which is the terminal opened by View | Tool Windows | Terminal as far as i understand).

(BTW can't see the image you added)

Thanks

**Comment by kornilova203** [comment]
I think this should help:
https://stackoverflow.com/questions/11046470/run-matlab-in-linux-without-graphical-environment/11046764
`matlab -nodesktop -nojvm -nosplash`
It should start a command-line interface (no graphical interface) where you can type commands, expressions.
Currently there is no other way to integrate matlab with an IDE, so plugin is mainly used for source code editing 

Sorry, here is the image:  
![](https://i.imgur.com/hIjMuId.png)

**Comment by YotamLif** [comment]
It is the same as before just that there is no matlab photo when opening the external command line :)
Hoped there is a way to integrate it somehow with the IDE but I understand there isn't one :(
Guess I should try Octave.
Are there any plans of matlab integration into the IDE (maybe even including the variables view like python variables in PyCharm)?

**Comment by kornilova203** [comment]
haha maybe you can just view it on image hosting: https://i.imgur.com/hIjMuId.png
No Octave integration also :,(
It would be great to make it possible to run/debug matlab/octave programs (with the variables view etc) but now it's hard for me to find time for this project :( so maybe I'll do it but I cannot guarantee
