### ISSUE TITLE
Plugin is shown to be incompatible when updating to PyCharm 2020.2

### ISSUE THREAD

**Issue by HaHeho** [kornilova203/matlab-IntelliJ-plugin#76]
Is there an actual reason for this or is it more of a (mis)configuration issue? Anyways, hope it can be resolved.

OSX 10.14.6 in case that matters.

**Comment by kornilova203** [comment]
This is strange... I didn't specify `until` build
I'll try to upload compatible plugin now

**Comment by kornilova203** [comment]
I've updated v0.7 that doesn't have `until` build
