### ISSUE TITLE
Wrong matching for "NEWLINE" depending on OS

### ISSUE THREAD

**Issue by GuillaumeTaffin** [kornilova203/matlab-IntelliJ-plugin#97]
I was trying to make the unit tests run on my **windows** machine but the MultifileResolveTest.kt "testGlobal" fails.

I think it comes from the fact windows newlines are "\r\n" and not only "\n".
The following screen shows teh test stopped in debug: 
![image](https://user-images.githubusercontent.com/73071259/102679598-c0b98300-417e-11eb-8abe-4bb8dc5dd9dc.png)

As you can see in the Variables section, the text of the refFile contains "\r\n" but the refFile.children ony matches "\n" as the NEWLINE PsiElement. Therefore, the refOffset index is wrong and the "findReferenceAt(..)" returns null. If it was called on "refOffset - 1" instead it would work fine but this would break on macOs or Linux.

I believe there is something wrong with the REGEX used to match new lines in the MatlabLexer.flex.
I tried to modify it, then re-generate the parser following the README... Unfortunately I'm new to this and it does not work, but I can't say if it is because of my REGEX or because I simply failed re-generating the parser.
My new REGEX was  the following : 
![image](https://user-images.githubusercontent.com/73071259/102679719-c1064e00-417f-11eb-94f1-235e0da1727c.png)

I could probably fix the test in a "dumb way" checking the OS for instance but I feel like this failure might reveal a weakness of the parser so I would prefer to solve it if it's the case.

Best regards,
Guillaume

**Comment by kornilova203** [comment]
Hello @GuillaumeTaffin,
Thank you for catching this issue.
IDE editor always converts line separators to `\n` so there is no need to modify lexer (.flex file)
I wrapped all usages of `File.readText()` with `convertLineSeparators` method in this commit 20efda81ba1640264f2b2ebc616ef669f128576f.
Please check if it works for you.

**Comment by GuillaumeTaffin** [comment]
Hi @kornilova203 all tests are green now on my side, thanks for the quick answer and the explanation about the line separator conversion made by the IDE.
I close this issue
