### ISSUE TITLE
Pass arguments to script

### ISSUE THREAD

**Issue by maxkraft7** [kornilova203/matlab-IntelliJ-plugin#98]
When I run my script in matlab I usually get the following notification if it needs additional arguments: 

![image](https://user-images.githubusercontent.com/49827312/102685930-63581d00-41e4-11eb-9584-3e6e7ee44436.png)

But whatever I put in the `Program arguments` Section in the `Run/Debug Configurations`-Window it always says `Not enough input arguments.`. How would I execute `MYFUNC('A','B')` from the matlab plugin?

![image](https://user-images.githubusercontent.com/49827312/102685980-c649b400-41e4-11eb-88da-b49694d338d9.png)

**Comment by kornilova203** [comment]
@maxkraft7,
Thank you for submitting the issue.
Currently program arguments are ignored. The only way is to create a separate file with `MYFUNC('A','B')` call and execute it
